version: '3.8'

services:
  crystord_web:
    image: crystord_web
    container_name: crystord_web
    labels:
      - traefik.enable=true
      - traefik.http.services.crystord.loadbalancer.server.port=4201
      - traefik.http.routers.crystord.rule=Host(`crystord.aleutheris.com`)
      - traefik.http.routers.crystord.tls=true
      - traefik.http.routers.crystord.tls.certresolver=le
    networks:
      - reverse_proxy_default
    restart: unless-stopped

networks:
  reverse_proxy_default:
    external: true
