# docker-compose.yml of crystord_web

services:
  crystord_web:
    image: crystord_web:dev
    container_name: crystord_web
    labels:
      - traefik.enable=true
      - traefik.http.services.crystord_web.loadbalancer.server.port=4201
      - traefik.http.routers.crystord_web.rule=Host(`crystord.com`)
      - traefik.http.routers.crystord_web.tls=true
      - traefik.http.routers.crystord_web.tls.certresolver=le
    ports:
      - "4201:4201"
    networks:
      - reverse_proxy_default
    restart: unless-stopped
networks:
  reverse_proxy_default:
    external: true
