import { readFileSync, writeFileSync } from 'fs'

// Mirrors crystord_app's deploy_config pattern: one `active` switch selects a
// named profile, and each profile references a Google OAuth client by name from
// the shared `oauthClients` map. The chosen profile is rendered into a
// build-time .env so Astro's static build bakes the right backend URL and
// Google client ID into the generated HTML.
const deployConfig = JSON.parse(readFileSync('deploy_config.json', 'utf-8'))
const active = deployConfig.active
const profile = deployConfig.profiles[active]

if (!profile) {
  console.error(`Unknown profile: "${active}". Available: ${Object.keys(deployConfig.profiles).join(', ')}`)
  process.exit(1)
}

if (!profile.graphqlEndpoint) {
  console.error(`Profile "${active}" is missing "graphqlEndpoint".`)
  process.exit(1)
}

// Resolve the oauthClient reference into a concrete googleClientId.
// A null/absent reference means "no Google sign-in" and resolves to an empty string.
const { oauthClient } = profile
let googleClientId = ''
if (oauthClient != null) {
  googleClientId = deployConfig.oauthClients[oauthClient]
  if (googleClientId == null) {
    console.error(`Profile "${active}" references unknown oauthClient: "${oauthClient}". ` +
      `Available: ${Object.keys(deployConfig.oauthClients).join(', ')}`)
    process.exit(1)
  }
}

// The marketing site's Sign In / Sign Up / Demo links and the post-auth token
// redirect point at the app. The app is often hosted on a different origin than
// the GraphQL API (e.g. app.crystord.com vs crystord.aleutheris.com/api), so a
// profile may set an explicit "appUrl". When absent we fall back to the GraphQL
// endpoint's origin (the historical behavior, for co-located deployments).
const origin = new URL(profile.appUrl ?? profile.graphqlEndpoint).origin

const env = {
  PUBLIC_APP_SIGN_IN_URL: `${origin}/sign-in`,
  PUBLIC_APP_SIGN_UP_URL: `${origin}/sign-up`,
  PUBLIC_APP_DEMO_URL: `${origin}/demo`,
  PUBLIC_APP_URL: origin,
  PUBLIC_GRAPHQL_URL: profile.graphqlEndpoint,
  PUBLIC_GOOGLE_CLIENT_ID: googleClientId,
}

const contents =
  `# Generated by scripts/config.mjs from deploy_config.json (active: "${active}").\n` +
  `# Do not edit by hand — change deploy_config.json and run \`npm run config\`.\n` +
  Object.entries(env).map(([k, v]) => `${k}=${v}`).join('\n') + '\n'

writeFileSync('.env', contents)
console.log(`.env written for profile: ${active} (oauthClient: ${oauthClient ?? 'none'})`)
